### PR TITLE
wasm-client: bump lightning terminal

### PR DESCRIPTION
**Pull request by ViktorTigerstrom**
This PR bumps the lightning-terminal version for the wasm-client.
We also add new features of that's been added to the lightning-terminal dependency since v0.10.X-alpha. Mainly subserver permissions have been added, and the inclusion of the taproot-assets cli, which we've added support for in the LNC WASM client example.

This PR currently uses a forked version on lightning-terminal, until a PR with the required change to the litclient Registrations have been merged.

Happy to address any feedback :)!

### CODE REVIEW

**Comment by ellemouton** [comment]
nice one @ViktorTigerstrom ! Can you open the other dependent PRs pls? the taro & lit one?

**Comment by ViktorTigerstrom** [comment]
The taproot-assets PR wasn't needed actually, but will open the lightning-terminal one @ellemouton!

**Comment by ViktorTigerstrom** [comment]
Updated the PR to use the latest version of the `lightning-terminal` branch now that the the required taproot-assets fix has been merged :rocket:!

I also included a commit aac8c8419fe33404fbd195a9c676f7fd88f82172 that replaces the `protobuf` dependency with 
the `google.golang.org` version, as I got warnings that the old version was deprecated.
I didn't replace it with our own forked version though (github.com/lightninglabs/protobuf-go-hex-display), as it currently isn't required to make the WASM client function.
If you think I should fixup this commit with the first `mod` commit, or that I should use our own forked version, let me know and I'll fix that :)!

**Comment by ellemouton** [comment]
nice! I think you can keep the commit that removes the deprecated version :) and no I dont think we need replace it with `protobuf-go-hex-display` if it is not yet used here

**Review by ellemouton — APPROVED** [review]
tACK, LGTM! :rocket:

**Pull request merged**
