### PR TITLE
cmd+example: update with Status server access

### PR DESCRIPTION
**Pull request by ellemouton**

### CODE REVIEW

**Comment by ViktorTigerstrom** [comment]
Pinging @ellemouton as I can't request a review from her, as she's the author of the PR :)! Would really appreciate if you'd be able to take a quick glance to see that the changes looks good!

**Comment by ViktorTigerstrom** [comment]
Reworded the commit as it now only edits `example/index.html`.

**Review by jamaljsr — APPROVED** [review]
tACK LGTM 🚀

I think we can merge this without @ellemouton's review since this is just the html changes.

**Review by itsrachelfish — APPROVED** [review]
tACK, confirmed that the example subserver RPC is working :+1: 

image

**Pull request merged**
